# Generated by Django 5.0.2 on 2024-03-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_marca_alter_cor_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marca",
            old_name="nacionalidae",
            new_name="nacionalidade",
        ),
    ]
